In [3]:
import pandas as pd
import pdfplumber
import csv

def find_next_containing_row(data_frame, start_index, column_index, text):
    for idx in range(start_index, len(data_frame)):
        cell_content = str(data_frame.iloc[idx, column_index])
        if pd.notna(cell_content) and text in cell_content:
            return idx
    return None

def find_first_non_empty_cell_and_extract_fee(data_frame, start_index, column_index):
    for idx in range(start_index, min(start_index + 10, len(data_frame))):
        cell_content = data_frame.iloc[idx, column_index]
        if pd.notna(cell_content) and cell_content != '':
            first_word = cell_content.split()[0]
            fee = ''.join(filter(str.isdigit, first_word))
            fee = fee.replace(',', '')
            return fee
    print("No non-empty cell found within the specified range.")
    return None

def clean_course_name(course_name):
    return str(course_name).replace('MSc in', 'MSc').strip()

def integrate_and_process_data(year):
    cleaned_fees_output_path = f'AllYears/CleanedFees{year}.csv'
    grouped_output_path = f'AllYears/Grouped_Fees{year}_by_Department_and_Level.csv'

    cleaned_fees_df = pd.read_csv(cleaned_fees_output_path)
    department_info_df = pd.read_csv('data/cleaned_output2804.csv', encoding='ISO-8859-1')

    def find_department(course_name, department_df):
        match = department_df[department_df['Course Name'].str.strip().eq(course_name.strip())]
        if not match.empty:
            return match['Department'].iloc[0]
        return "Department not found"

    cleaned_fees_df['Department'] = cleaned_fees_df['Course'].apply(lambda x: find_department(x, department_info_df))
    cleaned_fees_df['Home Fee'] = pd.to_numeric(cleaned_fees_df['Home Fee'], errors='coerce')
    cleaned_fees_df['Overseas Fee'] = pd.to_numeric(cleaned_fees_df['Overseas Fee'], errors='coerce')

    grouped_data = cleaned_fees_df.groupby(['Department', 'Level']).agg({
        'Home Fee': 'mean',
        'Overseas Fee': 'mean'
    }).reset_index()

    grouped_data.to_csv(grouped_output_path, index=False, encoding='utf-8-sig')
    print(f"Grouped data for {year} saved to:", grouped_output_path)

def extract_tables_from_pdf(pdf_path, output_csv_path):
    with pdfplumber.open(pdf_path) as pdf:
        all_tables = []
        for page in pdf.pages:
            tables = page.extract_tables()
            for table in tables:
                for row in table:
                    while len(row) < 10:
                        row.append('')
                    processed_row = row[:3] + [''] * 7
                    all_tables.append(processed_row)
        with open(output_csv_path, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile)
            for row in all_tables:
                writer.writerow(row)

for year in range(2018, 2025):
    pdf_path = f'Data/TuitionFees/Fees{year}.pdf'
    output_csv_path = f'AllYears/Fees{year}.csv'
    updated_all_courses_output_path = f'AllYears/CleanedFees{year}.csv'

    extract_tables_from_pdf(pdf_path, output_csv_path)
    fees_df = pd.read_csv(output_csv_path, encoding='latin-1')

    home_fee_index = find_next_containing_row(fees_df, 0, 1, "Home")
    undergrad_home_fee = find_first_non_empty_cell_and_extract_fee(fees_df, home_fee_index + 1, 1)
    overseas_fee_index = find_next_containing_row(fees_df, 0, 2, "Overseas")
    undergrad_overseas_fee = find_first_non_empty_cell_and_extract_fee(fees_df, overseas_fee_index + 1, 2)

    has_undergraduate = False
    all_courses_fees_detailed = []
    for index, row in fees_df.iterrows():
        if isinstance(row.iloc[0], str) and any(x in row.iloc[0] for x in ['BSc', 'BA', 'MSc']):
            course_name = clean_course_name(row.iloc[0].split(' - ')[0])
            level = "Postgraduate" if "MSc" in course_name else "Undergraduate"
            if level == "Undergraduate":
                has_undergraduate = True
            home_fee = row.iloc[1] if not pd.isna(row.iloc[1]) else (undergrad_home_fee if level == "Undergraduate" else '')
            overseas_fee = row.iloc[2] if not pd.isna(row.iloc[2]) else ''
            home_fee = ''.join(filter(str.isdigit, home_fee))
            overseas_fee = ''.join(filter(str.isdigit, overseas_fee))
            all_courses_fees_detailed.append([course_name, home_fee, overseas_fee, level])

    if not has_undergraduate:
        all_courses_fees_detailed.append(["Undergraduate Courses", undergrad_home_fee, undergrad_overseas_fee, "Undergraduate"])

    all_courses_df_detailed = pd.DataFrame(all_courses_fees_detailed, columns=['Course', 'Home Fee', 'Overseas Fee', 'Level'])
    all_courses_df_detailed.to_csv(updated_all_courses_output_path, index=False, encoding='utf-8-sig')

    print(f"Processed data for {year}.")
    integrate_and_process_data(year)

Processed data for 2018.
Grouped data for 2018 saved to: AllYears/Grouped_Fees2018_by_Department_and_Level.csv
Processed data for 2019.
Grouped data for 2019 saved to: AllYears/Grouped_Fees2019_by_Department_and_Level.csv
Processed data for 2020.
Grouped data for 2020 saved to: AllYears/Grouped_Fees2020_by_Department_and_Level.csv
Processed data for 2021.
Grouped data for 2021 saved to: AllYears/Grouped_Fees2021_by_Department_and_Level.csv
Processed data for 2022.
Grouped data for 2022 saved to: AllYears/Grouped_Fees2022_by_Department_and_Level.csv
Processed data for 2023.
Grouped data for 2023 saved to: AllYears/Grouped_Fees2023_by_Department_and_Level.csv
Processed data for 2024.
Grouped data for 2024 saved to: AllYears/Grouped_Fees2024_by_Department_and_Level.csv

In [4]:
import pandas as pd

# Load the CSV files
for year in range(2018,2025):
    globals()[f'fees_{year}'] = pd.read_csv(f'AllYears/Grouped_Fees{year}_by_Department_and_Level.csv')

# Initialize final merged DataFrame
final_merged_fees = fees_2024.rename(columns={
    'Home Fee': 'Home Fee_2024',
    'Overseas Fee': 'Overseas Fee_2024'
})

# Merge and rename for all years
for year in reversed(range(2018, 2024)):
    fees = eval(f'fees_{year}').rename(columns={
        'Home Fee': f'Home Fee_{year}',
        'Overseas Fee': f'Overseas Fee_{year}'
    })
    final_merged_fees = pd.merge(final_merged_fees, fees[['Department', 'Level', f'Home Fee_{year}', f'Overseas Fee_{year}']], 
                                 on=['Department', 'Level'], how='outer')

# Fill missing values
# Assuming universal fees are found in the 'fees_2022' DataFrame
universal_home_fee = fees_2022.loc[
    (fees_2022['Department'] == 'Department not found') & (fees_2022['Level'] == 'Undergraduate'),
    'Home Fee'
].values[0]
universal_overseas_fee = fees_2022.loc[
    (fees_2022['Department'] == 'Department not found') & (fees_2022['Level'] == 'Undergraduate'),
    'Overseas Fee'
].values[0]

# Fill missing undergraduate fees
for year in range(2018, 2025):
    final_merged_fees[f'Home Fee_{year}'].fillna(universal_home_fee, inplace=True)
    final_merged_fees[f'Overseas Fee_{year}'].fillna(universal_overseas_fee, inplace=True)

# Format fees to show only two decimal places
for year in range(2018, 2025):
    final_merged_fees[f'Home Fee_{year}'] = final_merged_fees[f'Home Fee_{year}'].astype(float).round(2)
    final_merged_fees[f'Overseas Fee_{year}'] = final_merged_fees[f'Overseas Fee_{year}'].astype(float).round(2)

# Display the final table
display(final_merged_fees)

,Department,Level,Home Fee_2024,Overseas Fee_2024,Home Fee_2023,Overseas Fee_2023,Home Fee_2022,Overseas Fee_2022,Home Fee_2021,Overseas Fee_2021,Home Fee_2020,Overseas Fee_2020,Home Fee_2019,Overseas Fee_2019,Home Fee_2018,Overseas Fee_2018
0,Department not found,Postgraduate,26493.71,30643.43,24956.53,28816.80,23257.56,26662.93,22518.67,25754.52,21482.42,24662.64,20178.65,23178.2,2.335713e+07,22347.77
1,Department not found,Undergraduate,9250.00,26940.00,9250.00,25188.00,9250.00,23330.00,9250.00,22430.00,9250.00,21570.00,9250.00,19920.0,9.250000e+03,19152.00
2,Department of Accounting,Postgraduate,35472.00,36168.00,33480.00,34128.00,31584.00,32208.00,30360.00,30960.00,29184.00,29760.00,28056.00,28608.0,2.697600e+04,27504.00
3,Department of Accounting,Undergraduate,9250.00,27192.00,9250.00,25656.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
4,Department of Anthropology,Undergraduate,9250.00,26184.00,9250.00,24720.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
5,Department of Economic History,Postgraduate,22452.00,28476.00,16440.00,25920.00,15816.00,24456.00,15216.00,23520.00,14640.00,22608.00,14088.00,21744.0,1.353600e+04,20904.00
6,Department of Economic History,Undergraduate,9250.00,26848.00,9250.00,25344.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
7,Department of Economics,Postgraduate,33144.00,33376.00,29700.00,30024.00,28020.00,28332.00,28080.00,28480.00,26992.00,27376.00,25952.00,26320.0,2.495200e+04,25304.00
8,Department of Economics,Undergraduate,9250.00,28176.00,9250.00,26592.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
9,Department of Finance,Postgraduate,40200.00,40548.00,37932.00,38256.00,35784.00,36096.00,34404.00,34704.00,33084.00,33372.00,31812.00,32088.0,3.058800e+04,30852.00
10,Department of Finance,Undergraduate,9250.00,28176.00,9250.00,26592.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
11,Department of Gender Studies,Postgraduate,17424.00,27480.00,16440.00,25920.00,15816.00,24456.00,15216.00,23520.00,14640.00,22608.00,14088.00,21744.0,1.353600e+04,20904.00
12,Department of Geography and Environment,Postgraduate,21165.33,29762.67,19973.33,27173.33,19098.67,25634.67,18133.33,24461.33,16794.00,23631.00,15483.00,22140.0,1.692156e+08,21123.43
13,Department of Geography and Environment,Undergraduate,9250.00,26688.00,9250.00,25188.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
14,Department of Government,Postgraduate,27480.00,27480.00,25920.00,25920.00,24456.00,24456.00,15216.00,23520.00,14640.00,22608.00,14088.00,21744.0,9.250000e+03,23330.00
15,Department of Government,Undergraduate,9250.00,26940.00,9250.00,25422.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
16,Department of Health Policy,Postgraduate,24664.00,29476.00,22836.00,27372.00,21744.00,25848.00,20928.00,24876.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
17,Department of International Development,Postgraduate,17424.00,27480.00,16440.00,25920.00,20136.00,24456.00,19368.00,23520.00,18624.00,22608.00,17916.00,21744.0,1.722000e+04,20904.00
18,Department of International History,Postgraduate,17424.00,27480.00,16440.00,25920.00,15816.00,24456.00,15216.00,23520.00,14640.00,22608.00,14088.00,21744.0,1.353600e+04,20904.00
19,Department of International History,Undergraduate,9250.00,26184.00,9250.00,24720.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
20,Department of International Relations,Undergraduate,9250.00,27192.00,9250.00,25656.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
21,Department of Management,Postgraduate,35472.00,36168.00,33480.00,34128.00,30246.00,30714.00,29076.00,29526.00,28500.00,28960.80,27412.40,27852.0,2.606880e+04,26491.20
22,Department of Management,Undergraduate,9250.00,27192.00,9250.00,25656.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
23,Department of Mathematics,Postgraduate,26448.00,31824.00,24960.00,30024.00,23700.00,28332.00,22788.00,27240.00,21912.00,26184.00,21072.00,25176.0,2.025600e+04,24204.00
24,Department of Mathematics,Undergraduate,9250.00,27192.00,9250.00,25656.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
25,Department of Media and Communications,Postgraduate,27480.00,27480.00,25920.00,25920.00,24456.00,24456.00,23520.00,23520.00,22608.00,22608.00,21744.00,21744.0,2.090400e+04,20904.00
26,Department of Methodology,Postgraduate,35472.00,36168.00,33480.00,34128.00,31584.00,32208.00,30360.00,30960.00,29184.00,29760.00,28056.00,28608.0,2.697600e+04,27504.00
27,Department of Philosophy Logic and Scientific ...,Postgraduate,22452.00,27480.00,25920.00,25920.00,24456.00,24456.00,23520.00,23520.00,22608.00,22608.00,21744.00,21744.0,2.090400e+04,20904.00
28,"Department of Philosophy, Logic and Scientific...",Undergraduate,9250.00,27520.00,9250.00,25968.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
29,Department of Psychological and Behavioural Sc...,Postgraduate,21931.20,27480.00,20692.80,25920.00,19713.60,24456.00,18960.00,23520.00,18230.40,22608.00,17534.40,21744.0,1.353600e+04,20904.00
30,Department of Psychological and Behavioural Sc...,Undergraduate,9250.00,26184.00,9250.00,24720.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
31,Department of Social Policy,Undergraduate,9250.00,26184.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
32,Department of Sociology,Postgraduate,18620.00,28720.00,17208.00,27076.00,18608.00,25836.00,18667.20,25348.80,17952.00,24369.60,17265.60,23433.6,1.735800e+04,22938.00
33,Department of Sociology,Undergraduate,9250.00,26184.00,9250.00,24720.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
34,Department of Statistics,Postgraduate,35472.00,37080.00,33480.00,34128.00,31584.00,32208.00,30360.00,30960.00,29184.00,29760.00,28056.00,28608.0,2.697600e+04,27504.00
35,Department of Statistics,Undergraduate,9250.00,27192.00,9250.00,25656.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
36,European Institute,Postgraduate,27480.00,27480.00,25920.00,25920.00,24456.00,24456.00,23520.00,23520.00,22608.00,22608.00,21744.00,21744.0,2.090400e+04,20904.00
37,Language Centre,Undergraduate,9250.00,26184.00,9250.00,24720.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,9250.00,23330.0,9.250000e+03,23330.00
38,Department of Social Policy,Postgraduate,9250.00,23330.00,9250.00,23330.00,9250.00,23330.00,15216.00,23520.00,14640.00,22608.00,14088.00,21744.0,1.072800e+04,20904.00